#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint
yarn prettifyCSS

yarn generate-translations 2> /dev/null

if [ ! $(git diff --name-only | grep locales | wc -l) -eq 0 ]; then
    echo >&2 "New strings found, please update translations";
    exit 1;
fi

echo "OK"
